### ISSUE TITLE
TopologyReader test is failing

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#114]
When I run expensive_test_topology_input.py I get this error:

Traceback (most recent call last):
  File "expensive_test_topology_input.py", line 101, in test_build_create_gmms
    t=IMP.pmi.topology.TopologyReader(topology_file)
  File "/Users/cgreen/imp_debug_clean/lib/IMP/pmi/topology/**init**.py", line 546, in **init**
    self.component_list=self.import_topology_file(topology_file)
  File "/Users/cgreen/imp_debug_clean/lib/IMP/pmi/topology/**init**.py", line 623, in import_topology_file
    new_component=self.create_component_topology(line, topology_fields, self.defaults, linenum)
  File "/Users/cgreen/imp_debug_clean/lib/IMP/pmi/topology/**init**.py", line 664, in create_component_topology
    t_chain = fields.index("chain").strip()
AttributeError: 'int' object has no attribute 'strip'

**Comment by benmwebb** [comment]
Well, this is hardly a surprise since this test has _always_ failed:
http://integrativemodeling.org/nightly/results/
But it looks easy enough to fix - I'll take a look.
