### ISSUE TITLE
When I build PMI I get doxygen errors

### ISSUE THREAD

**Issue by drussel** [salilab/pmi#13]
Traceback (most recent call last):
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 209, in <module>
    parse_file(sys.argv[1])
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 202, in parse_file
    handle_class(n, indent, printer)
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 145, in handle_class
    dump_class(c, meths, indent, printer)
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 126, in dump_class
    dump_function(m, indent + 4, printer)
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 111, in dump_function
    printer.output_lines(indent, d + [get_function_signature(func)],
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 72, in get_function_signature
    args = [format_arg(x) for x in args]
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 70, in format_arg
    sig += "=" + format_value(arg[1])
  File "/Users/drussel/src/imp/imp/tools/build/doxygen_filter_py.py", line 47, in format_value
    raise ValueError("Do not know how to format %s" % str(val))
ValueError: Do not know how to format <_ast.BinOp object at 0x1077f4710>

Not sure if it is a problem with the filter or with pmi.
@benmwebb

**Comment by benmwebb** [comment]
Yes, that's a problem with the filter. I'll fix.
