### ISSUE TITLE
Clustering step in IMP tutorial no longer works

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#139]
Running the IMP tutorial in `--test` mode; the [clustering step](http://integrativemodeling.org/nightly/doc/manual/rnapolii_4.html) fails:

```
$ python clustering.py  --test
...
getting coordinates for frame 45 rmf file ../modeling/output/rmfs//0.rmf3
Traceback (most recent call last):
  File "clustering.py", line 62, in <module>    density_custom_ranges=density_names)             # setup the list of densities to be calculated
  File "/clarinet1/home/ben/imp/release/lib/IMP/pmi/macros.py", line 1565, in clustering
DensModule.add_subunits_density(prot)
  File "/clarinet1/home/ben/imp/release/lib/IMP/pmi/analysis.py", line 1020, in add_subunits_density
IMP.atom.Molecule.setup_particle(h.get_particle())
  File "/clarinet1/home/ben/imp/release/lib/IMP/atom/__init__.py", line 9868, in setup_particle
return _IMP_atom.Molecule_setup_particle(*args)   
_IMP_kernel.UsageException: Usage check failure: Particle Rpb1 already set up as Molecule
```

**Comment by benmwebb** [comment]
`git bisect` reveals that the problematic commit is 33d4271e.
