### ISSUE TITLE
Issue with em.py

### ISSUE THREAD

**Issue by shanot** [salilab/pmi#142]
I added a test that fails in commit 8b3e7b8823a98159eb26ac88a31ea75dffd7502f with the following error:

```
======================================================================
ERROR: test_em_pmi (__main__.TestEMRestraint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_em_fit.py", line 129, in test_em_pmi
    target_radii_scale=3.0)
  File "/work/sam/imp-fast/lib/IMP/pmi/restraints/em.py", line 95, in __init__
    IMP.isd.gmm_tools.decorate_gmm_from_text(
UnboundLocalError: local variable 'IMP' referenced before assignment

----------------------------------------------------------------------
```

**Comment by cgreenberg** [comment]
@Pellarin Looks like it was having a problem due to isd_emxl. Since we're not currently using the alternatives to GaussianEMRestraint (pointwise...) I just removed it. Works now. Will commit.
