### ISSUE TITLE
test_io_crosslink.py has been failing

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#168]
@cgreenberg thanks for spotting that:

```
Traceback (most recent call last):
  File "test_io_crosslink.py", line 200, in test_quantitation_style
    cldb=IMP.pmi.io.crosslink.CrossLinkDataBase(cldbkc,list_parser=rplp)
  File "/Users/cgreen/imp_debug/lib/IMP/pmi/io/crosslink.py", line 334, in __init__
    self.converter=CrossLinkDataBaseKeywordsConverter.get_converter()
  File "/Users/cgreen/imp_debug/lib/IMP/pmi/io/crosslink.py", line 255, in get_converter
    self.check_keys()
  File "/Users/cgreen/imp_debug/lib/IMP/pmi/io/crosslink.py", line 207, in check_keys
    raise KeyError("CrossLinkDataBaseKeywordsConverter: must setup all necessary keys")
KeyError: 'CrossLinkDataBaseKeywordsConverter: must setup all necessary keys'
```

**Comment by Pellarin** [comment]
I had to make the CrossLinkDataBaseKeywordsConverter's construction depend on the ResiduePairListParser to check the keywords correctly.

closed by 0587f57d299a1d23af338864c301b1abe15f9383
