### ISSUE TITLE
analysis.Precision broken (TypeError: in method 'get_is_canonical') with PMI1 in latest IMP nightly

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#180]
Presumably caused by commit 363c924b2. e.g. running the IMP tutorial with the most recent IMP nightly build (salilab/imp@93e4707d):

```
Traceback (most recent call last):
  File "accuracy.py", line 43, in <module>
    pr.set_reference_structure(reference_rmf,0)
  File "/salilab/diva1/home/imp/develop/20160307-93e4707/lib/release64/IMP/pmi/analysis.py", line 905, in set_reference_structure
    particles_resolution_one,self.prots)
  File "/salilab/diva1/home/imp/develop/20160307-93e4707/lib/release64/IMP/pmi/analysis.py", line 674, in _select_coordinates
    if IMP.pmi.get_is_canonical(prot):
  File "/salilab/diva1/home/imp/develop/20160307-93e4707/lib/release64/IMP/pmi/__init__.py", line 1291, in get_is_canonical
    return _IMP_pmi.get_is_canonical(*args)
TypeError: in method 'get_is_canonical', argument 1 of type 'IMP::atom::Hierarchy'
```

**Comment by cgreenberg** [comment]
Can reproduce, fix coming...
