### ISSUE TITLE
Output error when resolution 0 only

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#34]
Traceback (most recent call last):
  File "em_atomic.py", line 142, in <module>
    rex.execute_macro()
  File "/Users/cgreen/imp_fast/lib/IMP/pmi/macros.py", line 193, in execute_macro
    output.write_pdb_best_scoring(score)
  File "/Users/cgreen/imp_fast/lib/IMP/pmi/output.py", line 186, in write_pdb_best_scoring
    self.write_pdb(filetoadd,appendmode=False)
  File "/Users/cgreen/imp_fast/lib/IMP/pmi/output.py", line 107, in write_pdb
    index_residue_pair_list[protname]=[(atom_index,resind)]
UnboundLocalError: local variable 'resind' referenced before assignment
[1]+  Terminated: 15          $IMPFAST python em_atomic.py

**Comment by Pellarin** [comment]
Yes.... it supports works only when you also have resolution 1

**Comment by cgreenberg** [comment]
Can that be fixed? Or do we need a new output class?

**Comment by Pellarin** [comment]
I'm trying to fix it right now

**Comment by Pellarin** [comment]
Now it is also faster because it cache the particles in the Output class. I added a test function.

**Comment by cgreenberg** [comment]
Now getting this error when trying to write with resolution 0:

  File "em_atomic.py", line 142, in <module>
    rex.execute_macro()
  File "/Users/cgreen/imp_fast/lib/IMP/pmi/macros.py", line 193, in execute_macro
    output.write_pdb_best_scoring(score)
  File "/Users/cgreen/imp_fast/lib/IMP/pmi/output.py", line 235, in write_pdb_best_scoring
    self.write_pdb(filetoadd,appendmode=False)
  File "/Users/cgreen/imp_fast/lib/IMP/pmi/output.py", line 64, in write_pdb
    for tupl in self.particle_infos_for_pdb[name]:
KeyError: 'out_atomic/pdbs//model.0.pdb'
