### ISSUE TITLE
doxygen

### ISSUE THREAD

**Issue by yannickspill** [salilab/pmi#63]
```
Traceback (most recent call last):
  File "/baycells/home/yannick/imp/src/tools/build/doxygen_filter_py.py", line 242, in <module>
    parse_file(sys.argv[1])
  File "/baycells/home/yannick/imp/src/tools/build/doxygen_filter_py.py", line 223, in parse_file
    a = ast.parse(("\n".join(lines)).rstrip() + '\n', fname)
  File "/usr/lib64/python2.6/ast.py", line 37, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "/baycells/home/yannick/imp/build-fast/doxygen/pmi/lib/IMP/pmi/sandbox.py", line 164
    self.components[(state_num,component_name,copy_num)]=
```

**Comment by benmwebb** [comment]
Well, obviously that's invalid Python and so can't be parsed. Fixed in 687ae099c4.
