### ISSUE TITLE
error upon running  test_representation_new.py 

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#65]
```
[pellarin@veena test]$ ~/imp-projects/imp-130614/imp-fast-mpich/setup_environment.sh python test_representation_new.py 
Traceback (most recent call last):
  File "test_representation_new.py", line 4, in <module>
    import IMP.pmi.representation_new as r
  File "/veena1/home/pellarin/imp-projects/imp-130614/imp-fast-mpich/lib/IMP/pmi/representation_new.py", line 5, in <module>
    import structure_tools
ImportError: No module named structure_tools
```

**Comment by cgreenberg** [comment]
I think you have to re-run cmake in order to pick up the new file.

**Comment by Pellarin** [comment]
OK thanks!
